# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        submodules: true
        dotnet-version: 7.0.x
    
    - name: Extract branch name
      shell: bash
      run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
      id: extract_branch
      
    # Update references
    - name: Git Sumbodule Update
      run: |
        git config --global user.email "polinetwork@outlook.com"
        git config --global user.name "PoliNetwork"
        git config --global pull.rebase false --allow-unrelated-histories
        git pull origin   ${{ steps.extract_branch.outputs.branch }} --recurse-submodules --allow-unrelated-histories
        git submodule update --remote --recursive  
        
    - name : ls
      run: |
        ls -l
        cd TestNugetPackage
        ls -l
      
      
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
