name: Run script

on:
  push:
    branches:
      - main
    paths:
      - "**.cs"
  schedule:
    - cron: 0 * * * *
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ["7.0.x"]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      # Update references
      - name: Git Submodule Update
        run: |
          git config --global user.email "polinetwork@outlook.com"
          git config --global user.name "PoliNetwork"
          git config --global pull.rebase false --allow-unrelated-histories
          git pull origin ${{ steps.extract_branch.outputs.branch }} --recurse-submodules --allow-unrelated-histories
          git submodule update --init --remote --recursive  
          git submodule update

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      ### SCHEDULE
      - name: Run (schedule)
        if: ${{ github.event_name == 'schedule' }}
        run: dotnet run --project ./GraduatorieScript/PoliNetwork.Graduatorie.Parser.csproj

      - name: Push generated files (schedule)
        if: ${{ github.event_name == 'schedule' }}
        uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
        with:
          add: "data"
          message: "[schedule] run script and update data"
          default_author: github_actions
          pathspec_error_handling: exitImmediately

      ### REPARSE (push, manual trigger)
      - name: Run (reparse)
        if: ${{ github.event_name != 'schedule' }}
        run: dotnet run --project ./GraduatorieScript/PoliNetwork.Graduatorie.Parser.csproj --reparse

      - name: Push generated files
        uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
        if: ${{ github.event_name != 'schedule' }}
        with:
          add: "data"
          message: "[reparse] run script and update data"
          default_author: github_actions
          pathspec_error_handling: exitImmediately
