name: Trigger RankingsDati workflow

on:
  push:
    branches:
      - main
    paths:
      - "**.cs"
  release:
    types: [published]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: update.yml
        repo: PoliNetworkOrg/RankingsDati
        inputs: '{ "is_release": ${{ github.event_name == ''release'' }} }'
